#!/bin/sh

function unload_scull ()
{
    rmmod scull || exit 1
    rm -f /dev/scull[0-3]
}

function unload_faulty ()
{
    rmmod faulty || exit 1
    rm -f /dev/faulty
}

function load_scull ()
{
    insmod /lib/modules/$(uname -r)/updates/scull.ko || exit 1
    local major=$(awk "\$2==\"scull\" {print \$1}" /proc/devices)
    local mode="666"
    rm -f /dev/scull[0-3]
    mknod /dev/scull0 c $major 0
    mknod /dev/scull1 c $major 1
    mknod /dev/scull2 c $major 2
    mknod /dev/scull3 c $major 3
    chmod $mode /dev/scull[0-3]
}

function load_faulty ()
{
    insmod /lib/modules/$(uname -r)/updates/faulty.ko || exit 1
    local major=$(awk "\$2==\"faulty\" {print \$1}" /proc/devices)
    local mode="666"
    rm -f /dev/faulty
    mknod /dev/faulty c $major 0
    chmod $mode /dev/faulty
}

case "$1" in
  start)
     echo "Loading scull device"
     load_scull
     echo "Loading faulty device"
     load_faulty
     echo "Loading hello device"
     modprobe hello
     echo "."
     ;;
  stop)
     echo "Unloading scull device"
     unload_scull
     echo "Unloading faulty device"
     unload_faulty
     echo "unloading hello device"
     rmmod hello
     echo "."
     ;;
  *)
     echo "Usage: $0 {start|stop}"
     exit 1
esac

exit 0